### ISSUE TITLE
can you please provide sample map ?

### ISSUE THREAD

**Issue by j-iv** [it-at-m/Kindona#6]
**Is your feature request related to a problem? Please describe.**
I was trying out Kindona and would absolutely appreciate a sample map. I'm not able to generate a mapforge map.

**Describe the solution you'd like**
assets/maps/campus_e.map a sample map added.

**Describe alternatives you've considered**

**Additional context**

**Comment by gregatm** [comment]
Hey, late response but I have added the sample map. Obviously, it only contains a small map cutout in munich. If no gps location is provided, the app should put you right with the mapped building. Otherwise scroll out really far and follow the tiles which do not show as "No Data"
