### ISSUE TITLE
Application not starting 

### ISSUE THREAD

**Issue by mukundsolanki** [it-at-m/Kindona#7]
I locally setup the project and tried to run it on a physical device with `flutter run`

And also build the apk with `flutter build apk`

But now while running the application it just shows a blank white screen, I also allowed the permissions for location and nearby devices, Is there anything else I need to setup?

**Comment by gregatm** [comment]
Have you build a map file? Maybe something went wrong there.

I have added a sample map that works. It has a small map cutout located in Munich and otherwise it should show you a lot of "No Data" tiles

**Comment by mukundsolanki** [comment]
Yeah I checked it and it's working now, thanks for your response!!
